# apiVersion: v1
# kind: Namespace
# metadata: 
#   name: server
# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: database-deployment
#   namespace: server
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: database
#   template:
#     metadata:
#       labels:
#         app: database
#     spec:
#       containers:
#       - name: database
#         image: mariadb:latest
#         ports:
#         - containerPort: 3306
#         env:
#         - name: MARIADB_ROOT_PASSWORD
#           value: docker@123
#         - name: MARIADB_DATABASE
#           value: main

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: database-service
#   namespace: server
# spec:
#   selector:
#     app.kubernetes.io/app: database
#   ports:
#     - protocol: TCP
#       port: 3306
#       targetPort: 3306