apiVersion: v1
kind: Namespace
metadata: 
  name: server
---
apiVersion: v1
kind: Pod
metadata:
  name: phpmyadmin
  namespace: server
spec:
  containers:
  - name: phpmyadmin
    image: phpmyadmin:latest
    ports:
    - containerPort: 80
    env:
    - name: PMA_HOST
      value: database-service.server.svc.cluster.local

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: backend
        image: stautvis/backend:latest
        ports:
          - containerPort: 80
            protocol: TCP
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
      - name: mariadb
        image: mariadb:latest
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: docker@123
        - name: MARIADB_DATABASE
          value: main

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: server
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: server

---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: server
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: server
