apiVersion: v1
kind: Namespace
metadata: 
  name: server
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: backend
        image: stautvis/backend:latest
        ports:
        - containerPort: 80
      - name: mariadb
        image: mariadb:latest
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: docker@123
        - name: MARIADB_DATABASE
          value: main

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: server
spec:
  selector:
    app.kubernetes.io/app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
